# Generated by Django 6.0.3 on 2026-04-16 20:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('product_type', models.CharField(choices=[('Almirah', 'Almirah'), ('Cooler', 'Cooler'), ('Stand', 'Stand'), ('Trunk', 'Trunk'), ('Other', 'Other')], max_length=50)),
                ('serial_number', models.CharField(db_index=True, max_length=120)),
                ('bill_copy', models.ImageField(upload_to='complaints/bills/')),
                ('technician_name', models.CharField(blank=True, max_length=120)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Process', 'In Process'), ('Resolved', 'Resolved')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Complaint',
                'verbose_name_plural': 'Complaints',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('subject', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contact Submission',
                'verbose_name_plural': 'Contact Submissions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HomepageBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('subtitle', models.CharField(blank=True, max_length=240)),
                ('image', models.ImageField(upload_to='banners/')),
                ('link_url', models.URLField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Homepage Banner',
                'verbose_name_plural': 'Homepage Banners',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50, unique=True)),
                ('customer_name', models.CharField(max_length=120)),
                ('customer_phone', models.CharField(max_length=20)),
                ('customer_address', models.TextField()),
                ('product_details', models.TextField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('delivery_status', models.CharField(choices=[('Booked', 'Booked'), ('Dispatched', 'Dispatched'), ('Delivered', 'Delivered')], default='Booked', max_length=20)),
                ('order_date', models.DateField(default=django.utils.timezone.localdate)),
                ('expected_delivery_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-order_date'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('ALMIRAH', 'Almirah'), ('COOLER', 'Cooler'), ('TRUNK', 'Trunk'), ('STAND', 'Stand')], max_length=50)),
                ('tagline', models.CharField(blank=True, help_text='Optional product tagline displayed on product cards.', max_length=120)),
                ('mrp', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('discount_percent', models.PositiveIntegerField(default=0, help_text='Enter discount percentage, e.g. 10 for 10% off. Leave 0 for no discount.')),
                ('stock_status', models.CharField(choices=[('In Stock', 'In Stock'), ('Out of Stock', 'Out of Stock')], default='In Stock', help_text='Set the availability status for this product.', max_length=20)),
                ('badge', models.CharField(blank=True, choices=[('New Arrival', 'New Arrival'), ('Best Seller', 'Best Seller'), ('Limited Edition', 'Limited Edition'), ('', 'None')], default='', help_text='Promotional badge for the product.', max_length=20)),
                ('available_colors', models.CharField(blank=True, help_text='Comma-separated list of available colors. Example: Black, Silver, #F2C94C', max_length=200)),
                ('dimensions', models.CharField(blank=True, help_text='Product dimensions, e.g. 1630x915x530 mm.', max_length=80)),
                ('description', models.TextField(blank=True)),
                ('meta_title', models.CharField(blank=True, max_length=120)),
                ('meta_description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('featured_offer', models.BooleanField(default=False, help_text='Display this product in the Special Offer section on the homepage.')),
                ('featured_popular', models.BooleanField(default=False, help_text='Display this product in the Popular Models section on the homepage.')),
                ('featured_homepage_almirah', models.BooleanField(default=False, help_text='Show this Almirah in the Almirah homepage section.')),
                ('featured_homepage_cooler', models.BooleanField(default=False, help_text='Show this Cooler in the Cooler homepage section.')),
                ('featured_homepage_trunk', models.BooleanField(default=False, help_text='Show this Trunk in the Trunk homepage section.')),
                ('featured_homepage_stand', models.BooleanField(default=False, help_text='Show this Stand in the Stand homepage section.')),
                ('featured_homepage', models.BooleanField(default=False, help_text='Legacy homepage flag; use the category-specific homepage fields instead.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SliderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(blank=True, max_length=120)),
                ('image', models.ImageField(upload_to='slider/')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Slider Image',
                'verbose_name_plural': 'Slider Images',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_name', models.CharField(max_length=120)),
                ('reviewer_email', models.EmailField(max_length=254)),
                ('product_type', models.CharField(choices=[('ALMIRAH', 'Almirah'), ('COOLER', 'Cooler'), ('TRUNK', 'Trunk'), ('STAND', 'Stand'), ('OTHER', 'Other')], default='ALMIRAH', max_length=30)),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('comment', models.TextField()),
                ('is_approved', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='store.product')),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SerialNumberRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=120, unique=True)),
                ('customer_name', models.CharField(max_length=120)),
                ('customer_phone', models.CharField(max_length=20)),
                ('customer_address', models.TextField(blank=True)),
                ('purchase_date', models.DateField()),
                ('warranty_expiry', models.DateField()),
                ('technician_name', models.CharField(blank=True, max_length=120)),
                ('product_checker_name', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.product')),
            ],
            options={
                'verbose_name': 'Serial Number Record',
                'verbose_name_plural': 'Serial Number Records',
                'ordering': ['-purchase_date'],
            },
        ),
    ]
