# Generated by Django 6.0.3 on 2026-04-12 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('product_type', models.CharField(choices=[('Almirah', 'Almirah'), ('Cooler', 'Cooler'), ('Stand', 'Stand'), ('Trunk', 'Trunk'), ('Other', 'Other')], max_length=50)),
                ('serial_number', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('purchase_date', models.DateField()),
                ('bill_copy', models.ImageField(upload_to='complaints/bills/')),
                ('message', models.TextField()),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=50)),
                ('customer_name', models.CharField(max_length=100)),
                ('product_details', models.TextField()),
                ('delivery_status', models.CharField(default='Processing', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('ALMIRAH', 'Almirah'), ('COOLER', 'Cooler'), ('TRUNK', 'Trunk Box'), ('STAND', 'Steel Stand')], max_length=50)),
                ('image', models.ImageField(upload_to='products/')),
                ('badge_text', models.CharField(blank=True, default='HEAVY DUTY STEEL', max_length=50)),
            ],
        ),
    ]
